language: haskell
ghc:
  - "8.4.3"

before_install:
  - sudo apt-get install python-tk supercollider
  - sudo pip install scipy numpy matplotlib
  - xvfb-run --server-args="-screen 0, 1280x800x24" sclang & sleep 5 ; kill %1

script:
  cd DSP-PBE && cabal configure --enable-tests && cabal install && cabal test

