language: haskell

branches:
  only:
    - master

env:
 - CABALVER=head GHCVER=8.4.3

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - sudo apt-get install python-tk supercollider
  - sudo pip install scipy numpy matplotlib
  - xvfb-run --server-args="-screen 0, 1280x800x24" sclang & sleep 5 ; kill %1
  - cd DSP-PBE

install:
  - cabal --version
  - ghc --version
  - travis_retry cabal update
  - cabal install

script:
  cabal new-test

